/// <reference types="node" />
export declare class BitsUtil {
    static BYTE_SIZE_IN_BYTES: number;
    static BOOLEAN_SIZE_IN_BYTES: number;
    static SHORT_SIZE_IN_BYTES: number;
    static CHAR_SIZE_IN_BYTES: number;
    static INT_SIZE_IN_BYTES: number;
    static FLOAT_SIZE_IN_BYTES: number;
    static LONG_SIZE_IN_BYTES: number;
    static DOUBLE_SIZE_IN_BYTES: number;
    static UUID_SIZE_IN_BYTES: number;
    static BIG_ENDIAN: number;
    static LITTLE_ENDIAN: number;
    static BEGIN_FLAG: number;
    static END_FLAG: number;
    static BEGIN_END_FLAG: number;
    static LISTENER_FLAG: number;
    static NULL_ARRAY_LENGTH: number;
    static FRAME_LENGTH_FIELD_OFFSET: number;
    static VERSION_FIELD_OFFSET: number;
    static FLAGS_FIELD_OFFSET: number;
    static TYPE_FIELD_OFFSET: number;
    static CORRELATION_ID_FIELD_OFFSET: number;
    static PARTITION_ID_FIELD_OFFSET: number;
    static DATA_OFFSET_FIELD_OFFSET: number;
    static HEADER_SIZE: number;
    static writeUInt32(buffer: Buffer, pos: number, val: number, isBigEndian: boolean): void;
    static writeUInt16(buffer: Buffer, pos: number, val: number, isBigEndian: boolean): void;
    static writeUInt8(buffer: Buffer, pos: number, val: number): void;
    static writeInt32(buffer: Buffer, pos: number, val: number, isBigEndian: boolean): void;
    static writeInt16(buffer: Buffer, pos: number, val: number, isBigEndian: boolean): void;
    static writeInt8(buffer: Buffer, pos: number, val: number): void;
    static writeFloat(buffer: Buffer, pos: number, val: number, isBigEndian: boolean): void;
    static writeDouble(buffer: Buffer, pos: number, val: number, isBigEndian: boolean): void;
    static readDouble(buffer: Buffer, pos: number, isBigEndian: boolean): number;
    static readFloat(buffer: Buffer, pos: number, isBigEndian: boolean): number;
    static readInt8(buffer: Buffer, pos: number): number;
    static readInt16(buffer: Buffer, pos: number, isBigEndian: boolean): number;
    static readInt32(buffer: Buffer, pos: number, isBigEndian: boolean): number;
    static readUInt8(buffer: Buffer, pos: number): number;
    static readUInt16(buffer: Buffer, pos: number, isBigEndian: boolean): number;
    static readUInt32(buffer: Buffer, pos: number, isBigEndian: boolean): number;
}
